# ~/.config/mpv/input.conf

# 全屏
ENTER cycle fullscreen
KP_ENTER cycle fullscreen

# 信息面板
i script-binding stats/display-stats-toggle

# 拖动/放大画面
meta+MBTN_LEFT script-binding enhanced_drag/drag-pan-free
Ctrl+MBTN_LEFT script-binding drag_zoom_box/drag-zoom-box

# 以鼠标位置为中心缩放；同时重置拖拽产生的 video-pan-x/y，缩放和拖拽是一体的状态
0 no-osd set video-zoom 0 ; no-osd set video-pan-x 0 ; no-osd set video-pan-y 0
KP0 no-osd set video-zoom 0 ; no-osd set video-pan-x 0 ; no-osd set video-pan-y 0
WHEEL_UP script-binding cursor-centric-zoom 0.1
WHEEL_DOWN script-binding cursor-centric-zoom -0.1

# 旋转
r script-message-to enhanced_rotation rotate-video 90
R script-message-to enhanced_rotation rotate-video -90
meta+r script-message-to enhanced_rotation rotate-video-reset

# 音量
UP    script-binding enhanced_volume/volume-up
DOWN  script-binding enhanced_volume/volume-down

# 快进
RIGHT script-binding enhanced_seek/seek-forward
LEFT  script-binding enhanced_seek/seek-backward

# 速度
c multiply speed 1.1
x multiply speed 1/1.1

# 设置 A / B
[ script-binding enhanced_ab_loop/set-a
] script-binding enhanced_ab_loop/set-b
{ script-binding enhanced_ab_loop/unset-a
} script-binding enhanced_ab_loop/unset-b
\ script-binding enhanced_ab_loop/show-state
、 script-binding enhanced_ab_loop/show-state
| script-binding enhanced_ab_loop/toggle-enabled

【 script-binding enhanced_ab_loop/set-a
】 script-binding enhanced_ab_loop/set-b
「 script-binding enhanced_ab_loop/unset-a
」 script-binding enhanced_ab_loop/unset-b

# 微调
Ctrl+[ script-binding enhanced_ab_loop/nudge-a-back
Ctrl+] script-binding enhanced_ab_loop/nudge-b-back
meta+[ script-binding enhanced_ab_loop/nudge-a-forward
meta+] script-binding enhanced_ab_loop/nudge-b-forward

Ctrl+【 script-binding enhanced_ab_loop/nudge-a-back
Ctrl+】 script-binding enhanced_ab_loop/nudge-b-back
meta+【 script-binding enhanced_ab_loop/nudge-a-forward
meta+】 script-binding enhanced_ab_loop/nudge-b-forward
